services:
  - type: web
    name: projectshelf-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGO_URI
        value: mongodb+srv://srinivasan:srinivashari@cluster0.gmtgxdz.mongodb.net/ProjectShelfdb?retryWrites=true&w=majority&appName=Cluster0
